'use client';

import React from 'react';
import { Wallet, Globe, ShieldCheck, Cpu, Database, BookOpen } from 'phosphor-react';
import { Card } from '@/components/ui/card';

export default function GuidePage() {
  return (
    <div className="max-w-5xl mx-auto px-4 py-8 space-y-12">
      {/* Header section */}
      <div className="space-y-4">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-500/10 text-blue-400 text-sm font-medium border border-blue-500/20">
          <BookOpen weight="duotone" />
          <span>User Guide</span>
        </div>
        <h1 className="text-4xl font-bold text-white tracking-tight">
          Getting Started with Blue Hole
        </h1>
        <p className="text-lg text-gray-400 max-w-2xl">
          Learn how to navigate the portal, connect your Maya wallet, and interact with the Ceiba Testnet ecosystem.
        </p>
      </div>

      {/* Grid of guides */}
      <div className="grid md:grid-cols-2 gap-6">
        
        {/* Wallet Connection */}
        <Card className="p-6 bg-gray-800/50 border-gray-700/50 hover:border-blue-500/50 transition-colors">
          <div className="w-12 h-12 rounded-xl bg-blue-500/20 text-blue-400 flex items-center justify-center mb-4">
            <Wallet size={24} weight="duotone" />
          </div>
          <h2 className="text-xl font-semibold text-white mb-2">Connecting Maya Wallet</h2>
          <p className="text-gray-400 mb-4 text-sm leading-relaxed">
            The Maya Wallet is your digital identity and passport to the BelizeChain. You need it to sign transactions, submit proposals, and claim testnet DALLA.
          </p>
          <ul className="space-y-2 text-sm text-gray-300">
            <li className="flex gap-2"><span className="text-blue-400">•</span> Install the Maya Wallet extension</li>
            <li className="flex gap-2"><span className="text-blue-400">•</span> Create a new account or import your seed phrase</li>
            <li className="flex gap-2"><span className="text-blue-400">•</span> Click the "Connect Wallet" button in the top right of this portal</li>
            <li className="flex gap-2"><span className="text-blue-400">•</span> Approve the connection request</li>
          </ul>
        </Card>

        {/* Portal Navigation */}
        <Card className="p-6 bg-gray-800/50 border-gray-700/50 hover:border-emerald-500/50 transition-colors">
          <div className="w-12 h-12 rounded-xl bg-emerald-500/20 text-emerald-400 flex items-center justify-center mb-4">
            <Globe size={24} weight="duotone" />
          </div>
          <h2 className="text-xl font-semibold text-white mb-2">Portal Navigation</h2>
          <p className="text-gray-400 mb-4 text-sm leading-relaxed">
            The Blue Hole Portal is divided into several administrative and exploratory zones.
          </p>
          <ul className="space-y-2 text-sm text-gray-300">
            <li className="flex gap-2"><span className="text-emerald-400 font-bold">Explorer:</span> View real-time blocks, extrinsics, and events on the Ceiba network.</li>
            <li className="flex gap-2"><span className="text-emerald-400 font-bold">Governance:</span> Participate in referenda, vote on network upgrades, and view council motions.</li>
            <li className="flex gap-2"><span className="text-emerald-400 font-bold">Treasury:</span> Monitor national reserve balances and spending proposals.</li>
            <li className="flex gap-2"><span className="text-emerald-400 font-bold">Validators:</span> Stake your tokens, nominate active validators, and track yields.</li>
          </ul>
        </Card>

        {/* KYC & Compliance */}
        <Card className="p-6 bg-gray-800/50 border-gray-700/50 hover:border-purple-500/50 transition-colors">
          <div className="w-12 h-12 rounded-xl bg-purple-500/20 text-purple-400 flex items-center justify-center mb-4">
            <ShieldCheck size={24} weight="duotone" />
          </div>
          <h2 className="text-xl font-semibold text-white mb-2">Identity & Compliance</h2>
          <p className="text-gray-400 mb-4 text-sm leading-relaxed">
            BelizeChain requires authorized identities for certain operations to ensure regulatory compliance.
          </p>
          <ul className="space-y-2 text-sm text-gray-300">
            <li className="flex gap-2"><span className="text-purple-400">•</span> Navigate to the Compliance tab</li>
            <li className="flex gap-2"><span className="text-purple-400">•</span> Submit your zero-knowledge proof generated by Pakit</li>
            <li className="flex gap-2"><span className="text-purple-400">•</span> Wait for the automated KYC verification layer to authorize your wallet address</li>
          </ul>
        </Card>

        {/* Advanced Integrations */}
        <Card className="p-6 bg-gray-800/50 border-gray-700/50 hover:border-amber-500/50 transition-colors">
          <div className="w-12 h-12 rounded-xl bg-amber-500/20 text-amber-400 flex items-center justify-center mb-4">
            <Cpu size={24} weight="duotone" />
          </div>
          <h2 className="text-xl font-semibold text-white mb-2">AI & Quantum Features</h2>
          <p className="text-gray-400 mb-4 text-sm leading-relaxed">
            Interact directly with our custom pallets utilizing off-chain workers.
          </p>
          <ul className="space-y-2 text-sm text-gray-300">
            <li className="flex gap-2"><span className="text-amber-400 font-bold">Nawal AI:</span> Submit federated learning gradients to the chain for decentralized model aggregation.</li>
            <li className="flex gap-2"><span className="text-amber-400 font-bold">Kinich Quantum:</span> Enqueue quantum circuits for secure execution via the testnet RPC.</li>
            <li className="flex gap-2"><span className="text-amber-400 font-bold">Pakit Storage:</span> Manage encrypted blobs and request ZK inclusion proofs.</li>
          </ul>
        </Card>

      </div>

      <div className="mt-12 p-8 rounded-2xl bg-gradient-to-br from-blue-900/40 to-blue-900/10 border border-blue-500/20 relative overflow-hidden">
        <div className="absolute inset-0 bg-[url('/noise.png')] opacity-10 mix-blend-overlay"></div>
        <div className="relative z-10 flex flex-col items-center text-center">
          <Database size={48} weight="duotone" className="text-blue-400 mb-4" />
          <h3 className="text-2xl font-bold text-white mb-2">Ready to explore?</h3>
          <p className="text-gray-400 mb-6 max-w-md">
            Connect your wallet to start signing transactions and interacting with the testnet.
          </p>
          <button className="px-6 py-3 bg-blue-500 hover:bg-blue-600 text-white font-medium rounded-lg shadow-lg shadow-blue-500/20 transition-all hover:-translate-y-0.5">
            Connect Maya Wallet
          </button>
        </div>
      </div>
    </div>
  );
}
